name: Publish as NPM Package
on:
  release:
    types: [published]
permissions:
  contents: write
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name pjdvmalan
          git config user.email pjdvmalan@hotmail.com
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Node.js Dependencies
        run: npm ci
      - name: Update package.json version
        run: |
          npm pkg set version=${{ github.event.release.tag_name }}
      - name: Commit and push version update
        run: |
          git add package.json
          git commit -m "chore(release): :bookmark: Updated Package Version to ${{ github.event.release.tag_name }} [skip-ci]"
          git pull --rebase origin main
          git push origin HEAD:main
      - name: Build, Lint and Publish NPM Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
